/// ***************************************************************
/// TODO: THIS FILE WAS JUST QUICKLY GENERATED BY LLM FOR TESTING PURPOSES AND NEEDS TO BE EDITED AND REVIEWED THOROUGHLY BEFORE USING!!!
/// ***************************************************************
const std = @import("std");
const builtin = @import("builtin");

comptime {
    _ = @import("sparse_solver.zig");
}

export fn add(a: f32, b: f32) f32 {
    return a + b;
}

// ---------------------------------------------------------
// libc Allocator Polyfills for Freestanding WASM ONLY
// ---------------------------------------------------------

comptime {
    if (builtin.target.cpu.arch == .wasm32) {
        _ = @import("c_allocator.zig");
    }
}
