/// ***************************************************************
/// TODO: THIS FILE WAS JUST QUICKLY GENERATED BY LLM FOR TESTING PURPOSES AND NEEDS TO BE EDITED AND REVIEWED THOROUGHLY BEFORE USING!!!
/// ***************************************************************

const std = @import("std");
const csparse = @import("interop/csparse.zig");

const allocator = std.heap.wasm_allocator;
const max_systems = 128;

const SparseSystem = struct {
    n: u32,
    capacity: u32,
    nnz: u32,

    rows: []i32,
    cols: []i32,
    vals: []f64,
    b: []f64,
    x: []f64,

    k_matrix: ?*csparse.cs = null, // pointer, not value
    S: ?csparse.css, // symbolic factorization
    N: ?csparse.csn, // numeric factorization
};

var systems: [max_systems]?*SparseSystem = [_]?*SparseSystem{null} ** max_systems;

fn getSystem(handle: i32) ?*SparseSystem {
    if (handle < 0 or handle >= max_systems) return null;
    return systems[@intCast(handle)];
}

fn buildK(sys: *SparseSystem) !void {
    // free any old K
    if (sys.kmatrix) |oldK| {
        csparse.spfree(&oldK);
        sys.kmatrix = null;
    }

    // triplet matrix T
    var T = try csparse.spalloc(@intCast(sys.n), @intCast(sys.n), @intCast(sys.nnz), 1, 1);
    // fill T from triplet buffers
    var k: usize = 0;
    while (k < sys.nnz) : (k += 1) {
        const i = sys.rows[k];
        const j = sys.cols[k];
        const v = sys.vals[k];
        try csparse.entry(&T, @intCast(i), @intCast(j), v);
    }

    // compress to CSC
    const K = try csparse.compress(T);
    csparse.spfree(&T);
    sys.kmatrix = K;
}

fn ensureSymbolic(sys: *SparseSystem) !void {
    if (sys.S != null) return;
    const K = &sys.kmatrix.?;
    const S = try csparse.schol(1, K.*); // order = 1: AMD
    sys.S = S;
}

fn refactorNumeric(sys: *SparseSystem) !void {
    // free old numeric factorization
    if (sys.N) |oldN| {
        csparse.nfree(&oldN);
        sys.N = null;
    }
    const K = &sys.kmatrix.?;
    const S = &sys.S.?;
    const N = try csparse.chol(K.*, S.*);
    sys.N = N;
}

export fn system_resize(handle: i32, new_n: u32) bool {
    const sys = getSystem(handle) orelse return false;
    if (new_n == sys.n) return true;

    const new_b = allocator.alloc(f64, new_n) catch return false;
    const new_x = allocator.alloc(f64, new_n) catch {
        allocator.free(new_b);
        return false;
    };

    allocator.free(sys.b);
    allocator.free(sys.x);
    sys.b = new_b;
    sys.x = new_x;
    sys.n = new_n;
    sys.nnz = 0; // triplet data is stale for new dimensions

    // Invalidate cached K — dimensions changed
    if (sys.k_matrix) |oldK| csparse.spfree(oldK);
    sys.k_matrix = null;

    return true;
}

export fn system_create(n: u32, capacity: u32) i32 {
    const sys = allocator.create(SparseSystem) catch return -1;

    sys.* = .{
        .n = n,
        .capacity = capacity,
        .nnz = 0,
        .rows = allocator.alloc(i32, capacity) catch {
            allocator.destroy(sys);
            return -1;
        },
        .cols = allocator.alloc(i32, capacity) catch {
            allocator.free(sys.rows);
            allocator.destroy(sys);
            return -1;
        },
        .vals = allocator.alloc(f64, capacity) catch {
            allocator.free(sys.cols);
            allocator.free(sys.rows);
            allocator.destroy(sys);
            return -1;
        },
        .b = allocator.alloc(f64, n) catch {
            allocator.free(sys.vals);
            allocator.free(sys.cols);
            allocator.free(sys.rows);
            allocator.destroy(sys);
            return -1;
        },
        .x = allocator.alloc(f64, n) catch {
            allocator.free(sys.b);
            allocator.free(sys.vals);
            allocator.free(sys.cols);
            allocator.free(sys.rows);
            allocator.destroy(sys);
            return -1;
        },
        .k_matrix = null,
        .S = null,
        .N = null,
    };

    for (systems, 0..) |slot, i| {
        if (slot == null) {
            systems[i] = sys;
            return @intCast(i);
        }
    }

    allocator.free(sys.x);
    allocator.free(sys.b);
    allocator.free(sys.vals);
    allocator.free(sys.cols);
    allocator.free(sys.rows);
    allocator.destroy(sys);
    return -1;
}

export fn system_solve(handle: i32, shape_dirty: bool, k_dirty: bool, f_dirty: bool) void {
    const sys = getSystem(handle) orelse return;

    if (shape_dirty or k_dirty) {
        // Free previous K
        if (sys.k_matrix) |oldK| csparse.spfree(oldK);
        sys.k_matrix = null;

        // Build triplet T
        const T = csparse.spalloc(@intCast(sys.n), @intCast(sys.n), @intCast(sys.nnz), 1, 1) catch return;

        var k: u32 = 0;
        while (k < sys.nnz) : (k += 1) {
            csparse.entry(T, sys.rows[@intCast(k)], sys.cols[@intCast(k)], sys.vals[@intCast(k)]) catch {
                csparse.spfree(T);
                return;
            };
        }

        // Compress → CSC
        const K = csparse.compress(T) catch {
            csparse.spfree(T);
            return;
        };
        csparse.spfree(T);
        sys.k_matrix = K;
    }

    if (shape_dirty or k_dirty or f_dirty) {
        // Copy b → x, then solve in-place
        @memcpy(sys.x, sys.b);

        const K = sys.k_matrix orelse return;
        csparse.cholsol(1, K, sys.x.ptr) catch return;
    }
}

export fn system_rows_ptr(handle: i32) u32 {
    const sys = getSystem(handle) orelse return 0;
    return @intFromPtr(sys.rows.ptr);
}

export fn system_cols_ptr(handle: i32) u32 {
    const sys = getSystem(handle) orelse return 0;
    return @intFromPtr(sys.cols.ptr);
}

export fn system_vals_ptr(handle: i32) u32 {
    const sys = getSystem(handle) orelse return 0;
    return @intFromPtr(sys.vals.ptr);
}

export fn system_b_ptr(handle: i32) u32 {
    const sys = getSystem(handle) orelse return 0;
    return @intFromPtr(sys.b.ptr);
}

export fn system_x_ptr(handle: i32) u32 {
    const sys = getSystem(handle) orelse return 0;
    return @intFromPtr(sys.x.ptr);
}

export fn system_set_nnz(handle: i32, nnz: u32) void {
    const sys = getSystem(handle) orelse return;
    sys.nnz = nnz;
}

export fn system_destroy(handle: i32) void {
    const idx: usize = @intCast(handle);
    const sys = getSystem(handle) orelse return;

    allocator.free(sys.x);
    allocator.free(sys.b);
    allocator.free(sys.vals);
    allocator.free(sys.cols);
    allocator.free(sys.rows);
    allocator.destroy(sys);
    systems[idx] = null;
}
