/// ***************************************************************
/// TODO: THIS FILE WAS JUST QUICKLY GENERATED BY LLM FOR TESTING PURPOSES AND NEEDS TO BE EDITED AND REVIEWED THOROUGHLY BEFORE USING!!!
/// ***************************************************************
const std = @import("std");

/// CSparse matrix representation.
///
/// A matrix is stored either as:
/// - Triplet (builder form): `nz >= 0`
/// - CSC (compressed sparse column): `nz == -1`
///
/// Row/column indices are 0-based.
pub const cs = extern struct {
    /// Allocated nonzero capacity for `i`/`p`/`x` storage.
    nzmax: i64,
    /// Number of rows.
    m: i64,
    /// Number of columns.
    n: i64,
    /// Triplet: column indices (size `nzmax`). CSC: column pointers (size `n+1`).
    p: [*c]i64,
    /// Row indices (size `nzmax`).
    i: [*c]i64,
    /// Numerical values (size `nzmax`), can be null for pattern-only matrices.
    x: [*c]f64,
    /// Triplet: current nnz (`>= 0`). CSC: always `-1`.
    nz: i64,
};

/// Symbolic factorization result (structure/ordering, no numeric factors).
pub const css = extern struct {
    /// Inverse permutation (fill reduction).
    pinv: [*c]i64,
    /// Column permutation for LU/QR paths.
    q: [*c]i64,
    /// Elimination tree parent array.
    parent: [*c]i64,
    /// Symbolic column pointers / counts.
    cp: [*c]i64,
    /// QR helper array.
    leftmost: [*c]i64,
    m2: i64,
    /// Predicted nnz(L).
    lnz: f64,
    /// Predicted nnz(U) or nnz(R).
    unz: f64,
};

/// Numeric factorization result.
pub const csn = extern struct {
    /// Lower factor.
    L: [*c]cs,
    /// Upper factor (unused for pure Cholesky).
    U: [*c]cs,
    pinv: [*c]i64,
    /// QR-specific workspace.
    B: [*c]f64,
};

/// Dulmage-Mendelsohn permutation results.
pub const csd = extern struct {
    p: [*c]i64,
    q: [*c]i64,
    r: [*c]i64,
    s: [*c]i64,
    nb: i64,
    rr: [5]i64,
    cc: [5]i64,
};

/// Wrapper error set for CSparse operations.
pub const Error = error{
    OutOfMemory,
    OperationFailed,
    FactorizationFailed,
};

/// Raw CSparse allocation entrypoint.
///
/// - `m`: row count.
/// - `n`: column count.
/// - `nzmax`: initial nonzero capacity.
/// - `values`: `1` allocates numeric storage (`x`), `0` keeps pattern-only matrix.
/// - `triplet`: `1` creates triplet form (`nz >= 0`), `0` creates CSC form (`nz == -1`).
///
/// Returns null on failure.
pub extern fn cs_spalloc(m: i64, n: i64, nzmax: i64, values: i64, triplet: i64) ?*cs;

/// Raw CSparse free entrypoint.
///
/// Frees sparse matrix and its internal buffers.
/// Returns null for chaining, matching CSparse C API.
pub extern fn cs_spfree(A: ?*cs) ?*cs;

/// Raw CSparse resize entrypoint.
///
/// - `A`: matrix to resize.
/// - `nzmax`: new capacity; `<= 0` means "fit to current nnz".
///
/// Returns non-zero on success, zero on failure.
pub extern fn cs_sprealloc(A: ?*cs, nzmax: i64) i64;

/// Raw CSparse triplet insertion entrypoint.
///
/// Appends one entry `(i, j, x)` into triplet matrix `T`.
/// Returns non-zero on success, zero on failure.
pub extern fn cs_entry(T: ?*cs, i: i64, j: i64, x: f64) i64;

/// Raw CSparse conversion entrypoint.
///
/// Converts triplet matrix into CSC format.
/// Returns newly allocated matrix or null on failure.
pub extern fn cs_compress(T: ?*cs) ?*cs;

/// Raw CSparse add entrypoint.
///
/// Computes `alpha * A + beta * B` and returns newly allocated CSC matrix.
/// Returns null on failure.
pub extern fn cs_add(A: ?*cs, B: ?*cs, alpha: f64, beta: f64) ?*cs;

/// Raw CSparse transpose entrypoint.
///
/// - `values`: `1` transposes numeric values too, `0` transposes pattern only.
///
/// Returns newly allocated transposed matrix or null on failure.
pub extern fn cs_transpose(A: ?*cs, values: i64) ?*cs;

/// Raw CSparse symbolic analysis entrypoint.
///
/// - `order`: ordering mode (`0` natural, `1` AMD).
///
/// Returns symbolic factorization or null on failure.
pub extern fn cs_schol(order: i64, A: ?*cs) ?*css;

/// Raw CSparse symbolic free entrypoint.
pub extern fn cs_sfree(S: ?*css) ?*css;

/// Raw CSparse numeric factorization entrypoint.
///
/// Computes numeric Cholesky factorization using matrix `A` and symbolic `S`.
/// Returns numeric factorization or null on failure.
pub extern fn cs_chol(A: ?*cs, S: ?*css) ?*csn;

/// Raw CSparse numeric free entrypoint.
pub extern fn cs_nfree(N: ?*csn) ?*csn;

/// Raw CSparse solve entrypoint.
///
/// - `order`: ordering mode (`0` natural, `1` AMD).
/// - `A`: input matrix (CSC expected).
/// - `b`: in/out RHS vector; overwritten in-place with solution `x`.
///
/// Returns non-zero on success, zero on failure.
pub extern fn cs_cholsol(order: i64, A: ?*cs, b: [*c]f64) i64;

/// Raw CSparse duplicate removal entrypoint.
///
/// Removes duplicate entries from matrix, summing values.
/// Returns non-zero on success, zero on failure.
pub extern fn cs_dupl(A: ?*cs) i64;

/// Raw CSparse matrix-vector multiply entrypoint.
///
/// Computes `y += A * x`.
/// Returns non-zero on success, zero on failure.
pub extern fn cs_gaxpy(A: ?*cs, x: [*c]f64, y: [*c]f64) i64;

/// Raw CSparse matrix-matrix multiply entrypoint.
///
/// Computes `C = A * B` and returns newly allocated CSC matrix.
/// Returns null on failure.
pub extern fn cs_multiply(A: ?*cs, B: ?*cs) ?*cs;

/// Raw CSparse AMD ordering entrypoint.
///
/// - `order`: ordering mode (`0` natural, `1` just AMD, `2` AMD then postorder).
///
/// Returns permutation vector, or null (zero pointer) on failure.
pub extern fn cs_amd(order: i64, A: ?*cs) [*c]i64;

/// Raw CSparse inverse permute entrypoint.
///
/// Computes `x(p) = b`.
/// Returns non-zero always.
pub extern fn cs_ipvec(p: [*c]i64, b: [*c]f64, x: [*c]f64, n: i64) i64;

/// Raw CSparse forward triangular solve entrypoint.
///
/// Solves `L * x = x` in-place with lower triangular L.
/// Returns non-zero on success, zero on failure.
pub extern fn cs_lsolve(L: ?*cs, x: [*c]f64) i64;

/// Raw CSparse backward triangular solve entrypoint.
///
/// Solves `L' * x = x` in-place with lower triangular L.
/// Returns non-zero on success, zero on failure.
pub extern fn cs_ltsolve(L: ?*cs, x: [*c]f64) i64;

/// Raw CSparse invert permutation entrypoint.
///
/// Returns inverse of permutation `p`, or null (zero pointer) on failure.
pub extern fn cs_pinv(p: [*c]i64, n: i64) [*c]i64;

/// Raw CSparse permute vector entrypoint.
///
/// Computes `x = b(p)`.
/// Returns non-zero always.
pub extern fn cs_pvec(p: [*c]i64, b: [*c]f64, x: [*c]f64, n: i64) i64;

/// Raw CSparse symmetric permutation entrypoint.
///
/// Computes `C = A(p,p)` where `pinv` is the inverse of `p`.
/// - `values`: `1` permutes numeric values too, `0` pattern-only.
///
/// Returns newly allocated matrix or null on failure.
pub extern fn cs_symperm(A: ?*cs, pinv: [*c]i64, values: i64) ?*cs;

/// Raw CSparse dmperm free entrypoint.
pub extern fn cs_dfree(D: ?*csd) ?*csd;

/// Raw CSparse memory free entrypoint.
///
/// Frees a pointer allocated via cs_malloc, cs_calloc, cs_realloc, cs_pinv, cs_amd, etc.
pub extern fn cs_free(p: ?*anyopaque) ?*anyopaque;

/// Safe wrapper for `cs_spalloc`.
///
/// - `m`: row count.
/// - `n`: column count.
/// - `nzmax`: initial nonzero capacity.
/// - `values`: `1` allocates numeric storage (`x`), `0` pattern-only matrix.
/// - `triplet`: `1` triplet form (for `entry`), `0` CSC form.
///
/// Returns `error.OutOfMemory` on failure.
pub fn spalloc(m: i64, n: i64, nzmax: i64, values: i64, triplet: i64) Error!*cs {
    return cs_spalloc(m, n, nzmax, values, triplet) orelse error.OutOfMemory;
}

/// Safe wrapper for `cs_spfree`.
///
/// Frees sparse matrix and its internal buffers.
pub fn spfree(A: ?*cs) void {
    _ = cs_spfree(A);
}

/// Safe wrapper for `cs_sprealloc`.
///
/// - `A`: matrix to resize.
/// - `nzmax`: target capacity, `<= 0` means fit to current nnz.
///
/// Returns `error.OperationFailed` on failure.
pub fn sprealloc(A: *cs, nzmax: i64) Error!void {
    if (cs_sprealloc(A, nzmax) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_entry`.
///
/// Appends one triplet entry `(i, j, x)`.
/// Returns `error.OperationFailed` on failure.
pub fn entry(T: *cs, i: i64, j: i64, x: f64) Error!void {
    if (cs_entry(T, i, j, x) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_compress`.
///
/// Converts triplet matrix into CSC and returns newly allocated matrix.
/// Returns `error.OperationFailed` on failure.
pub fn compress(T: *cs) Error!*cs {
    return cs_compress(T) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_add`.
///
/// Computes `alpha * A + beta * B` and returns newly allocated matrix.
/// Returns `error.OperationFailed` on failure.
pub fn add(A: *cs, B: *cs, alpha: f64, beta: f64) Error!*cs {
    return cs_add(A, B, alpha, beta) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_transpose`.
///
/// - `values`: `1` transposes values too, `0` pattern-only transpose.
///
/// Returns newly allocated transposed matrix.
/// Returns `error.OperationFailed` on failure.
pub fn transpose(A: *cs, values: i64) Error!*cs {
    return cs_transpose(A, values) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_schol`.
///
/// - `order`: ordering mode (`0` natural, `1` AMD).
///
/// Returns symbolic factorization.
/// Returns `error.OperationFailed` on failure.
pub fn schol(order: i64, A: *cs) Error!*css {
    return cs_schol(order, A) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_sfree`.
pub fn sfree(S: ?*css) void {
    _ = cs_sfree(S);
}

/// Safe wrapper for `cs_chol`.
///
/// Returns numeric factorization.
/// Returns `error.OperationFailed` on failure.
pub fn chol(A: *cs, S: *css) Error!*csn {
    return cs_chol(A, S) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_nfree`.
pub fn nfree(N: ?*csn) void {
    _ = cs_nfree(N);
}

/// Safe wrapper for `cs_cholsol`.
///
/// - `order`: ordering mode (`0` natural, `1` AMD).
/// - `A`: input matrix in CSC format.
/// - `b`: in/out RHS vector; overwritten in-place with solution `x`.
///
/// Returns `error.FactorizationFailed` on solve failure.
pub fn cholsol(order: i64, A: *cs, b: [*c]f64) Error!void {
    if (cs_cholsol(order, A, b) == 0) return error.FactorizationFailed;
}

/// Safe wrapper for `cs_dupl`.
///
/// Removes duplicate entries from matrix, summing values.
/// Returns `error.OperationFailed` on failure.
pub fn dupl(A: *cs) Error!void {
    if (cs_dupl(A) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_gaxpy`.
///
/// Computes `y += A * x`.
/// Returns `error.OperationFailed` on failure.
pub fn gaxpy(A: *cs, x: [*c]f64, y: [*c]f64) Error!void {
    if (cs_gaxpy(A, x, y) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_multiply`.
///
/// Computes `C = A * B` and returns newly allocated CSC matrix.
/// Returns `error.OperationFailed` on failure.
pub fn multiply(A: *cs, B: *cs) Error!*cs {
    return cs_multiply(A, B) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_amd`.
///
/// - `order`: ordering mode (`0` natural, `1` just AMD, `2` AMD then postorder).
///
/// Returns permutation vector.
/// Returns `error.OperationFailed` on failure.
pub fn amd(order: i64, A: *cs) Error![*c]i64 {
    const result = cs_amd(order, A);
    if (@intFromPtr(result) == 0) return error.OperationFailed;
    return result;
}

/// Safe wrapper for `cs_ipvec`.
///
/// Computes `x(p) = b`. Always succeeds.
pub fn ipvec(p: [*c]i64, b: [*c]f64, x: [*c]f64, n: i64) void {
    _ = cs_ipvec(p, b, x, n);
}

/// Safe wrapper for `cs_lsolve`.
///
/// Solves `L * x = x` in-place with lower triangular L.
/// Returns `error.OperationFailed` on failure.
pub fn lsolve(L: *cs, x: [*c]f64) Error!void {
    if (cs_lsolve(L, x) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_ltsolve`.
///
/// Solves `L' * x = x` in-place with lower triangular L.
/// Returns `error.OperationFailed` on failure.
pub fn ltsolve(L: *cs, x: [*c]f64) Error!void {
    if (cs_ltsolve(L, x) == 0) return error.OperationFailed;
}

/// Safe wrapper for `cs_pinv`.
///
/// Returns inverse of permutation `p`.
/// Returns `error.OperationFailed` on failure.
pub fn pinv(p: [*c]i64, n: i64) Error![*c]i64 {
    const result = cs_pinv(p, n);
    if (@intFromPtr(result) == 0) return error.OperationFailed;
    return result;
}

/// Safe wrapper for `cs_pvec`.
///
/// Computes `x = b(p)`. Always succeeds.
pub fn pvec(p: [*c]i64, b: [*c]f64, x: [*c]f64, n: i64) void {
    _ = cs_pvec(p, b, x, n);
}

/// Safe wrapper for `cs_symperm`.
///
/// Computes `C = A(p,p)` where `p_inv` is the inverse of `p`.
/// - `values`: `1` permutes numeric values too, `0` pattern-only.
///
/// Returns newly allocated matrix.
/// Returns `error.OperationFailed` on failure.
pub fn symperm(A: *cs, p_inv: [*c]i64, values: i64) Error!*cs {
    return cs_symperm(A, p_inv, values) orelse error.OperationFailed;
}

/// Safe wrapper for `cs_dfree`.
pub fn dfree(D: ?*csd) void {
    _ = cs_dfree(D);
}

/// Safe wrapper for `cs_free`.
///
/// Frees a pointer allocated by CSparse.
pub fn free(p: ?*anyopaque) void {
    _ = cs_free(p);
}

/// Converts CSparse matrix to a row-major dense vector of length `m*n`.
///
/// - `allocator`: allocator used for output buffer.
/// - `A`: input sparse matrix (triplet or CSC).
///
/// Caller owns and must free the returned slice with the same allocator.
pub fn toDense(allocator: std.mem.Allocator, A: *const cs) ![]f64 {
    const rows: usize = @intCast(A.m);
    const cols: usize = @intCast(A.n);
    const dense = try allocator.alloc(f64, rows * cols);
    @memset(dense, 0.0);

    if (A.nz >= 0) {
        // Triplet format
        const nz: usize = @intCast(A.nz);
        var k: usize = 0;
        while (k < nz) : (k += 1) {
            const row: usize = @intCast(A.i[k]);
            const col: usize = @intCast(A.p[k]);
            dense[row * cols + col] += A.x[k];
        }
    } else {
        // Compressed-column format (CSC)
        var j: usize = 0;
        while (j < cols) : (j += 1) {
            const start: usize = @intCast(A.p[j]);
            const end: usize = @intCast(A.p[j + 1]);
            var idx = start;
            while (idx < end) : (idx += 1) {
                const row: usize = @intCast(A.i[idx]);
                dense[row * cols + j] = A.x[idx];
            }
        }
    }

    return dense;
}

const testing = std.testing;

fn buildTriDiag4() Error!*cs {
    const T = try spalloc(4, 4, 12, 1, 1);
    try entry(T, 0, 0, 4);
    try entry(T, 0, 1, 1);
    try entry(T, 1, 0, 1);
    try entry(T, 1, 1, 4);
    try entry(T, 1, 2, 1);
    try entry(T, 2, 1, 1);
    try entry(T, 2, 2, 4);
    try entry(T, 2, 3, 1);
    try entry(T, 3, 2, 1);
    try entry(T, 3, 3, 4);
    const A = try compress(T);
    spfree(T);
    return A;
}

test "csparse: spalloc and spfree" {
    const T = try spalloc(4, 4, 12, 1, 1);
    defer spfree(T);
    try testing.expect(T.nz >= 0);
    try testing.expectEqual(@as(i64, 4), T.m);
    try testing.expectEqual(@as(i64, 4), T.n);

    const C = try spalloc(3, 2, 0, 1, 0);
    defer spfree(C);
    try testing.expectEqual(@as(i64, -1), C.nz);
    try testing.expectEqual(@as(i64, 3), C.m);
    try testing.expectEqual(@as(i64, 2), C.n);
}

test "csparse: entry and compress" {
    const A = try buildTriDiag4();
    defer spfree(A);

    try testing.expectEqual(@as(i64, -1), A.nz);
    const p = A.p;
    try testing.expectEqual(@as(i64, 0), p[0]);
    try testing.expectEqual(@as(i64, 2), p[1]);
    try testing.expectEqual(@as(i64, 5), p[2]);
    try testing.expectEqual(@as(i64, 8), p[3]);
    try testing.expectEqual(@as(i64, 10), p[4]);
}

test "csparse: dupl" {
    const T = try spalloc(2, 2, 4, 1, 1);
    try entry(T, 0, 0, 2.0);
    try entry(T, 0, 0, 3.0);
    try entry(T, 0, 1, 1.0);
    try entry(T, 1, 1, 4.0);
    const A = try compress(T);
    spfree(T);
    defer spfree(A);

    try dupl(A);
    const dense = try toDense(testing.allocator, A);
    defer testing.allocator.free(dense);

    try testing.expectApproxEqAbs(@as(f64, 5.0), dense[0], 1e-10);
    try testing.expectApproxEqAbs(@as(f64, 1.0), dense[1], 1e-10);
    try testing.expectApproxEqAbs(@as(f64, 0.0), dense[2], 1e-10);
    try testing.expectApproxEqAbs(@as(f64, 4.0), dense[3], 1e-10);
}

test "csparse: gaxpy" {
    const A = try buildTriDiag4();
    defer spfree(A);

    var x = [_]f64{ 1.0, 2.0, 3.0, 4.0 };
    var y = [_]f64{0.0} ** 4;

    try gaxpy(A, @ptrCast(&x), @ptrCast(&y));

    try testing.expectEqual(@as(f64, 6.0), y[0]);
    try testing.expectEqual(@as(f64, 12.0), y[1]);
    try testing.expectEqual(@as(f64, 18.0), y[2]);
    try testing.expectEqual(@as(f64, 19.0), y[3]);
}

test "csparse: multiply" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const C = try multiply(A, A);
    defer spfree(C);

    const dense = try toDense(testing.allocator, C);
    defer testing.allocator.free(dense);

    try testing.expectEqual(@as(f64, 17.0), dense[0]);
    try testing.expectEqual(@as(f64, 8.0), dense[1]);
    try testing.expectEqual(@as(f64, 1.0), dense[2]);
    try testing.expectEqual(@as(f64, 0.0), dense[3]);
    try testing.expectEqual(@as(f64, 8.0), dense[4]);
    try testing.expectEqual(@as(f64, 18.0), dense[5]);
    try testing.expectEqual(@as(f64, 8.0), dense[6]);
    try testing.expectEqual(@as(f64, 1.0), dense[7]);
    try testing.expectEqual(@as(f64, 1.0), dense[8]);
    try testing.expectEqual(@as(f64, 8.0), dense[9]);
    try testing.expectEqual(@as(f64, 18.0), dense[10]);
    try testing.expectEqual(@as(f64, 8.0), dense[11]);
    try testing.expectEqual(@as(f64, 0.0), dense[12]);
    try testing.expectEqual(@as(f64, 1.0), dense[13]);
    try testing.expectEqual(@as(f64, 8.0), dense[14]);
    try testing.expectEqual(@as(f64, 17.0), dense[15]);
}

test "csparse: add" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const C = try add(A, A, 1.0, 1.0);
    defer spfree(C);

    const dense = try toDense(testing.allocator, C);
    defer testing.allocator.free(dense);

    try testing.expectEqual(@as(f64, 8.0), dense[0]);
    try testing.expectEqual(@as(f64, 2.0), dense[1]);
    try testing.expectEqual(@as(f64, 0.0), dense[2]);
    try testing.expectEqual(@as(f64, 0.0), dense[3]);
    try testing.expectEqual(@as(f64, 2.0), dense[4]);
    try testing.expectEqual(@as(f64, 8.0), dense[5]);
    try testing.expectEqual(@as(f64, 2.0), dense[6]);
    try testing.expectEqual(@as(f64, 0.0), dense[7]);
    try testing.expectEqual(@as(f64, 0.0), dense[8]);
    try testing.expectEqual(@as(f64, 2.0), dense[9]);
    try testing.expectEqual(@as(f64, 8.0), dense[10]);
    try testing.expectEqual(@as(f64, 2.0), dense[11]);
    try testing.expectEqual(@as(f64, 0.0), dense[12]);
    try testing.expectEqual(@as(f64, 0.0), dense[13]);
    try testing.expectEqual(@as(f64, 2.0), dense[14]);
    try testing.expectEqual(@as(f64, 8.0), dense[15]);
}

test "csparse: transpose" {
    const T = try spalloc(2, 3, 6, 1, 1);
    try entry(T, 0, 0, 1.0);
    try entry(T, 0, 1, 2.0);
    try entry(T, 0, 2, 3.0);
    try entry(T, 1, 0, 4.0);
    try entry(T, 1, 1, 5.0);
    try entry(T, 1, 2, 6.0);
    const A = try compress(T);
    spfree(T);
    defer spfree(A);

    const B = try transpose(A, 1);
    defer spfree(B);

    try testing.expectEqual(@as(i64, 3), B.m);
    try testing.expectEqual(@as(i64, 2), B.n);
}

test "csparse: sprealloc" {
    const T = try spalloc(4, 4, 5, 1, 1);
    defer spfree(T);
    try entry(T, 0, 0, 42.0);

    const old_nzmax = T.nzmax;
    try sprealloc(T, 20);
    try testing.expect(T.nzmax >= 20);
    try testing.expect(T.nzmax != old_nzmax);

    const A = try compress(T);
    defer spfree(A);
    const dense = try toDense(testing.allocator, A);
    defer testing.allocator.free(dense);
    try testing.expectEqual(@as(f64, 42.0), dense[0]);
}

test "csparse: ipvec, pvec, pinv" {
    var p = [_]i64{ 2, 0, 3, 1 };
    var b = [_]f64{ 10.0, 20.0, 30.0, 40.0 };
    var x = [_]f64{0.0} ** 4;

    pvec(@ptrCast(&p), @ptrCast(&b), @ptrCast(&x), 4);
    try testing.expectEqual(@as(f64, 30.0), x[0]);
    try testing.expectEqual(@as(f64, 10.0), x[1]);
    try testing.expectEqual(@as(f64, 40.0), x[2]);
    try testing.expectEqual(@as(f64, 20.0), x[3]);

    ipvec(@ptrCast(&p), @ptrCast(&b), @ptrCast(&x), 4);
    try testing.expectEqual(@as(f64, 20.0), x[0]);
    try testing.expectEqual(@as(f64, 40.0), x[1]);
    try testing.expectEqual(@as(f64, 10.0), x[2]);
    try testing.expectEqual(@as(f64, 30.0), x[3]);

    const inv = try pinv(@ptrCast(&p), 4);
    defer free(@ptrCast(inv));
    try testing.expectEqual(@as(i64, 1), inv[0]);
    try testing.expectEqual(@as(i64, 3), inv[1]);
    try testing.expectEqual(@as(i64, 0), inv[2]);
    try testing.expectEqual(@as(i64, 2), inv[3]);
}

test "csparse: lsolve and ltsolve" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const S = try schol(0, A);
    defer sfree(S);

    const N = try chol(A, S);
    defer nfree(N);

    const L: *cs = @ptrCast(N.L);

    const b = [_]f64{ 1.0, 2.0, 3.0, 4.0 };
    var x = b;

    try lsolve(L, @ptrCast(&x));
    try ltsolve(L, @ptrCast(&x));

    var Ax = [_]f64{0.0} ** 4;
    try gaxpy(A, @ptrCast(&x), @ptrCast(&Ax));

    try testing.expectApproxEqAbs(b[0], Ax[0], 1e-10);
    try testing.expectApproxEqAbs(b[1], Ax[1], 1e-10);
    try testing.expectApproxEqAbs(b[2], Ax[2], 1e-10);
    try testing.expectApproxEqAbs(b[3], Ax[3], 1e-10);
}

test "csparse: symperm" {
    const A = try buildTriDiag4();
    defer spfree(A);

    var p_inv = [_]i64{ 1, 3, 0, 2 };
    const C = try symperm(A, @ptrCast(&p_inv), 1);
    defer spfree(C);

    try testing.expectEqual(@as(i64, 4), C.m);
    try testing.expectEqual(@as(i64, 4), C.n);
    try testing.expect(C.p[4] > 0);
}

test "csparse: amd" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const perm = try amd(1, A);
    defer free(@ptrCast(perm));

    try testing.expect(perm[0] >= 0);
    try testing.expect(perm[3] >= 0);
}

test "csparse: schol, chol, sfree, nfree" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const S = try schol(1, A);
    try testing.expect(S.pinv != null);

    const N = try chol(A, S);
    try testing.expect(N.L != null);

    sfree(S);
    nfree(N);
}

test "csparse: cholsol" {
    const A = try buildTriDiag4();
    defer spfree(A);

    var b = [_]f64{ 1.0, 1.0, 1.0, 1.0 };
    const b_orig = b;

    try cholsol(1, A, @ptrCast(&b));

    var Ax = [_]f64{0.0} ** 4;
    try gaxpy(A, @ptrCast(&b), @ptrCast(&Ax));

    try testing.expectApproxEqAbs(b_orig[0], Ax[0], 1e-10);
    try testing.expectApproxEqAbs(b_orig[1], Ax[1], 1e-10);
    try testing.expectApproxEqAbs(b_orig[2], Ax[2], 1e-10);
    try testing.expectApproxEqAbs(b_orig[3], Ax[3], 1e-10);
}

test "csparse: toDense" {
    const A = try buildTriDiag4();
    defer spfree(A);

    const dense = try toDense(testing.allocator, A);
    defer testing.allocator.free(dense);

    try testing.expectEqual(@as(f64, 4.0), dense[0]);
    try testing.expectEqual(@as(f64, 1.0), dense[1]);
    try testing.expectEqual(@as(f64, 0.0), dense[2]);
    try testing.expectEqual(@as(f64, 0.0), dense[3]);
    try testing.expectEqual(@as(f64, 1.0), dense[4]);
    try testing.expectEqual(@as(f64, 4.0), dense[5]);
    try testing.expectEqual(@as(f64, 1.0), dense[6]);
    try testing.expectEqual(@as(f64, 0.0), dense[7]);
    try testing.expectEqual(@as(f64, 0.0), dense[8]);
    try testing.expectEqual(@as(f64, 1.0), dense[9]);
    try testing.expectEqual(@as(f64, 4.0), dense[10]);
    try testing.expectEqual(@as(f64, 1.0), dense[11]);
    try testing.expectEqual(@as(f64, 0.0), dense[12]);
    try testing.expectEqual(@as(f64, 0.0), dense[13]);
    try testing.expectEqual(@as(f64, 1.0), dense[14]);
    try testing.expectEqual(@as(f64, 4.0), dense[15]);
}

test "csparse: dfree" {
    dfree(null);
}
